services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
        - "27017:27017"