services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql